/*
  * Authors: Team 1
  * Created: 06 November 2020
  * License: Public Domain
  * Random Image Generator Code borrowed from: https://www.javatpoint.com/oprweb/test.jsp?filename=random-image-generator-in-javascript1
*/

function getRandomImage() {
//declare an array to store the images
var randomImage = new Array();

//insert the URL of images in array
randomImage[0] = "img/door1.png";
randomImage[1] = "img/door2.jpg";
randomImage[2] = "img/door3.jpg";
randomImage[3] = "img/door4.jpg";
randomImage[4] = "img/door5.jpg";
randomImage[5] = "img/door6.jpg";
randomImage[6] = "img/door7.jpg";
randomImage[7] = "img/door8.jpg";
randomImage[8] = "img/door9.jpg";
randomImage[9] = "img/door10.jpg";
randomImage[10] = "img/door11.jpg";
randomImage[11] = "img/door12.jpg";
randomImage[12] = "img/door13.jpg";
randomImage[13] = "img/door14.jpg";
randomImage[14] = "img/door15.jpg";

//generate a number and provide to the image to generate randomly
var number = Math.floor(Math.random()*randomImage.length);

//return the images generated by a random number
return '<img class="img-responsive" src="'+randomImage[number]+'" />';
}
$(".door").append(getRandomImage())
$(".door2").append(getRandomImage())
$(".door3").append(getRandomImage())
$(".door4").append(getRandomImage())
$(".door5").append(getRandomImage())
$(".door6").append(getRandomImage())
$(".door7").append(getRandomImage())
$(".door8").append(getRandomImage())
$(".door9").append(getRandomImage())
$(".door10").append(getRandomImage())
$(".door11").append(getRandomImage())
$(".door12").append(getRandomImage())
